version: '3'

services:
  e-stock-broker:    
    build:
      context: .
      dockerfile: rabbit-mq-plugins.dockerfile
    image: e-stock-broker:1.0.3.0
    ports:
      - "15672:15672"  #Management
      - "5672:5672"    #AMQP
      - "25672:25672"  #clustering
      
      - "1883:1883"    #mqtt
      - "15675:15675"  #http/web-mqtt

      - "61613:61613"  #stomp
      - "15674:15674"  #http/web-stomp
    environment:
      RABBITMQ_DEFAULT_USER: ${ADMIN_USER}
      RABBITMQ_DEFAULT_PASS: ${ADMIN_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    volumes:
      - e-stock-broker:/var/lib/rabbitmq/mnesia
    container_name: e-stock-broker
volumes:
  e-stock-broker: